apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: contract-test
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: collectionName
        description: The name of the POSTMAN collection 
      - name: collectionEnvironment
        description: The name of the environment the collection
      - name: imageUrl
        description: Url of image repository
        default: url
      - name: imageTag
        description: Tag of the images to be used.
        default: "latest"
  steps:
    - name: step-contract-test
      image: miqui/postman-docker:latest
      command: ["run"]
      args:
        - "$(inputs.params.collectionName)"
        - "-e environments/$(inputs.params.collectionEnvironment)"
        - "-r cli"
