apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: contract-test
spec:
  inputs:
    resources:
      - name: git
        type: git
    params:
      - name: collectionName
        description: The name of the POSTMAN collection 
      - name: collectionEnvironment
        description: The name of the environment the collection
      - name: sourceDir
        description: the source dir
        default: "src"
      - name: imageTag
        description: Tag of the images to be used.
        default: "latest"

  steps:
    - name: step-contract-test
      image: "miqui/postman-docker:$(inputs.params.imageTag)"
      workingDir: "/workspace/$(inputs.params.sourceDir)"
      args:
        - run $(inputs.params.collectionName) -e environments/$(inputs.params.collectionEnvironment) -r cli
        
