apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: contract-test-
spec:
  serviceAccountName: service-account
  taskRef:
    name:  contract-test
  inputs:
   resources:
    - name: git
      resourceRef:
        name: git
   params:
    - name: collectionName
      value: Restful_Booker_Collection.json
    - name: collectionEnvironment
      value: Restful_Booker_Environment.json